services:
  nginx:
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
      network: net_inception
    container_name: nginx
    ports:
      - 443:8043
    env_file: srcs/.env
    init: true
    restart: on-failure
      #    secrets:
      #      server-certificate:
      #        - xxx
      #        # to place into /run/secrets/<secret_name>
    stop_signal: SIGTERM
########################################

  mariadb:
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
      network: net_inception
    container_name: mariadb
    ports:
      - 3306:3306
    volumes: /var/abarrier/data/mysql:/var/lib/mysql
    depends_on:
      nginx:
        condition: service_healthy
    env_file: srcs/.env
    init: true
    restart: on_failure
    stop_signal: SIGTERM
      #  secrets:
      #    server-certification:
      #      file:
      #        - ./server.cert
