services:
  mariadb:
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    container_name: mariadb
    networks:
      - inception
    ports:
      - 3306
    volumes:
      - mariadb:/var/lib/mysql
      #    depends_on:
      #      nginx:
      #        condition: service_healthy
    env_file: env
    init: true
    restart: unless-stopped
    stop_signal: SIGTERM
      #	    secrets:
      #	      server-certificate:
      #	        - xxx
      #	        # to place into /run/secrets/<secret_name>
      ########################################
  nginx:
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx
    networks:
      - inception
    ports:
      - 443
    env_file: env
    init: true
    restart: on-failure
    stop_signal: SIGTERM
      #	    secrets:
      #	      server-certificate:
      #	        - xxx
      #	        # to place into /run/secrets/<secret_name>
      ########################################
volumes:
  mariadb:
    driver: local
    name: mariadb
    driver_opts:
      type: none
      o: bind
      device: /home/abarrier/data/mariadb
      ########################################
networks:
  inception:
    driver: bridge
